### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ya2ro#37]
ya2ro does not have tests. I would like integration tests (e.g., with other tools/packages) and tool tests to assess functionality (for example, if there are missing fields, empty readmes, etc.)

**Comment by PavelAntonia** [comment]
Tests added:

* End-to-end testing of all input types and functionalities (paper, paper with doi, project and landing page)
* Integration tests with other modules such as: somef, scc
* All supported fields by ya2ro are tested
