### ISSUE TITLE
ya2ro configuration is confusing

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/ya2ro#38]
Now there is a properties file (which by browsing the help it is not clear what it does), and a configuration. 

The difference between them, or why 2 options are needed is not clear. I would expect the properties file to add the github access token if needed. If there is none, state a warning and proceed without access token

**Comment by PavelAntonia** [comment]
The "-c / --configure" flag has been deleted. From now on, the user will have to insert his token in the properties file. 

When isn't configured, the following message will be printed:

`WARNING: GITHUB_PERSONAL_ACCESS_TOKEN is not configured. Please add your personal token in ya2ro configuration file.
        --> /Users/github/ya2ro/src/ya2ro/resources/properties.yaml <--

        ADD a line like the following:
        GITHUB_PERSONAL_ACCESS_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

        ya2ro will continue working, but is highly recommended to apply this setting.`

**Comment by dgarijo** [comment]
This is not what the documentation currently states, See https://github.com/oeg-upm/ya2ro#usage
I will reopen the issue until this is fixed.

**Comment by PavelAntonia** [comment]
Thanks for pointing that out! I just updated the documentation.
