### ISSUE TITLE
Using Citation.cff as base yaml

### ISSUE THREAD

**Issue by B3J4y** [oeg-upm/ya2ro#61]
Hi @dgarijo , 
I saw your presentation at the DaMaLOS Conference and I was impressed by your work. I was just wondering about your decision to instantiate a new yaml file. From my perspective, you could integrate all the information into the citation.cff and use this file as a starting point for creating a landing page. From your data wrapper file, I noticed the following objects:

* Contact: [Contact](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#contact)
* Project: Could be represented
  with [References](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsreference)
* Paper: [Credit Redirection](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide. md#credit-redirection)
* Author: [Author](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#authors)
* Dataset: You can specify a [type](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#references) in the Citation.cff or use [References](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#references) to show that there is a dataset linked to the software.
* Demo: This is hard but could also be done with [References](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionsreference)
* Bibliograhpy Entry: [References](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#references)

This message should not be seen as a critique, but as support for your work. I've discussed this repository with @sdruskat, and we both agree that it represents a gap in the CFF universe that needs to be filled. Your process could help create a more human-readable interface, and it would also enhance the value of the machine-readable part, as repository owners would greatly benefit from a well-documented machine-readable file. Maybe we'll find a way to integrate it into the cff context, and I am also interested to help rewrite the code to use cff as configuration file.

What do you think about this?

**Comment by dgarijo** [comment]
Hi @B3J4y,
thanks for your support and feedback.
I think the scope of this project is slightly different, as it includes wrapping ROs that may contain no software entities and hence no citation.cff files; or projects with multiple source code repositories, and therefore multiple cff files.

That said, if you want we can create a new project for wrapping up the ROs specifically to software projects, based on the citation file. We can use some of the ideas/code from here if useful, and fix/evolve whatever is necessary. Happy to participate on that.

**Comment by B3J4y** [comment]
Thank you for your clarification, @dgarijo. 

I'm glad to hear that we could use your work to narrow the variety of software projects. From my perspective, we could reuse the entire HTML generation part and simply adjust the data input to the citation.cff.  But before planning further steps, I hope the mention of Stephan Druskat worked, and we could find with him a place in the cff-universe to integrate this.

**Comment by dgarijo** [comment]
Sure, let me know if you want to discuss this further

**Comment by sdruskat** [comment]
Hi @dgarijo and @B3J4y, the mention worked.

I'd be happy to discuss a solution similar to this one for singular software projects. Could even be a nice student project? Perhaps this issue tracker isn't the right place for it, but I cannot yet point to another one that's better suited (another gap in the CFF universe).

Depending on your own motivation, @B3J4y, feel free to start a new repo for collaboration. We can discuss inclusion in the CFF org later as well.

**Comment by B3J4y** [comment]
@sdruskat, the mention worked 🥳

I've also considered transforming it into a student project. But this will delay this project for about 6 months, and there's a risk that the quality might not meet expectations.

@dgarijo, I appreciate your cff2ro idea as it links the two works by name. However, if one looks at the work without its historical context, the 'RO' part isn't obvious since the repository is considered a research object even without this little helper. What do you think about 'cff2pages'? The goal of the project becomes clearer with this name.

**Comment by B3J4y** [comment]
Hey @dgarijo,
I apologize, I got a little too excited about this project and couldn't wait for the conclusion of our discussion. I've already started the cff2pages repository and did some work on it over the weekend. If you'd like to participate, please visit the repository at https://github.com/University-of-Potsdam-MM/cff2pages, or we could arrange a digital meeting. I look forward to hearing from you. I'm closing this issue as there's nothing more to be addressed here. Thanks for the discussion.

**Comment by dgarijo** [comment]
@B3J4y great! Is there anything you'd like me to do? Not sure about the scope that you are aiming for with the project.

**Comment by B3J4y** [comment]
@dgarijo, I updated the README yesterday to make our project easier to understand. If you still have questions or have any
suggestions, feel free to let me know.

I would greatly appreciate your involvement in any aspect of the development process, be it defining requirements,
implementing features, or simply testing the product through usage. Do you have any specific areas of interest, or does
the project still seem too broad for effective engagement? I am sorry, I am not the best at involving people into
projects.
